### ISSUE TITLE
[BUG] Newly created accounts can't login even after enabling them.

### ISSUE THREAD

**Issue by melcarthus** [BoltAuth/Auth#35]
After adding an account the account looks disabled. But when I check the checkbox for the account and click the 'enable' button, I still can't login afterwards.

If I go into the edit account a second time and add a new/or the same password again the account wil log in.

Details
-------

 - Relevant Bolt Auth Version: [ 3.0.5 | master ]
 - Relevant Bolt Version: [ 3.5.3 ]
 - PHP version: [ 7.0 ]
 - For UX/UI issues: [ Chrome Version 67.0.3396.87 (Official Build) (64-bit) ]

Happens on /bolt/extensions/auth
Add 11 accounts, you will see that there are only 10 visible.
Change 10 to 20 for example here: [https://github.com/BoltAuth/Auth/blob/f1080cec5e805b907be9c84d2943d5d2de1ed7a8/src/Controller/Backend.php#L177-L179](url) 
and you will see the accounts are still there, just no pagination.

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:
​
other plugins that are installed
Seo 1.10
BoltForms 4.2.3
EmailSpooler 3.1.1
Sitemap 2.5.0
google/recaptcha 1.1.3
pagerfanta/pagerfanta 1.1.0
Paragonie/random_compat 2.0.15
ramsey/uuid 3.7.3

**Comment by Epoxyde** [comment]
Hi,
I have similar issue, after creating a new user from auth admin page, I can not login with this new user and got this error:
> Login details are incorrect.

But if I edit the user profil from the admin page and set the passwords again, then I can login.

**EDIT:**
After further investigations, I notice that after adding a new user from admin options, the "password" column in bolt_auth_oauth table is empty for the new user.

**EDIT 2:**
Fixed by adding  
>$oauth->setPassword($entity->getPassword());

in line 273 of boltauth/auth/src/Controller/Backend.php:

**Details**
Bolt Auth Version: [ 3.0.5 ]
Bolt Version: [ 3.5.3 ]
[ Firefox Quantum for Ubuntu 60.0.2 ]

**Comment by SvanteRichter** [comment]
Should have been fixed in #39 which was released in v3.0.7

Let me know if it wasn't
